# Generated by Django 6.0 on 2026-02-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_id'),
        ('authentication', '0006_customuser_is_doctor_verified'),
    ]

    operations = [
    ]
