# Generated by Django 6.0 on 2026-02-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_customuser_is_doctor_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Consultation fee per appointment', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('ADMIN', 'Admin')], default='PATIENT', max_length=10),
        ),
    ]
