# Generated by Django 4.2.27 on 2026-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_customuser_consultation_fee_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="specialization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARDIOLOGIST", "Cardiologist (Heart)"),
                    ("ENDOCRINOLOGIST", "Endocrinologist (Diabetes & Thyroid)"),
                    ("NEPHROLOGIST", "Nephrologist (Kidney)"),
                    ("HEPATOLOGIST", "Hepatologist (Liver)"),
                    ("HEMATOLOGIST", "Hematologist (Anemia)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
