# Generated by Django 6.0 on 2026-02-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportresult_doctor_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportresult',
            name='suggested_specialization',
            field=models.CharField(blank=True, help_text='Specialization suggested for follow-up', max_length=50, null=True),
        ),
    ]
