# Generated by Django 6.0 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientlink',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20),
        ),
    ]
