# Generated by Django 6.0 on 2026-02-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorpatientlink_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlicense',
            name='other_certificates',
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doctor_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='doctor.doctorlicense')),
            ],
        ),
    ]
