# Generated by Django 4.2.27 on 2026-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_alter_doctoravailability_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="clinical_observations",
            field=models.TextField(
                blank=True,
                help_text="Doctor's clinical observations during this visit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctorpatientlink",
            name="clinical_observations",
            field=models.TextField(
                blank=True,
                help_text="Medical notes and observations by the doctor",
                null=True,
            ),
        ),
    ]
