# Generated by Django 4.2.28 on 2026-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_appointment_refund_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="admin_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Commission for admin (25%)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Net revenue for doctor",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Custom label for this slot (e.g., 'Morning Clinic')",
                max_length=50,
                null=True,
            ),
        ),
    ]
