# Generated by Django 6.0 on 2026-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_specialization_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_doctor_verified',
            field=models.BooleanField(default=False),
        ),
    ]
