# Generated by Django 6.0 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_20260209_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='doctor_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('GENERAL_PHYSICIAN', 'General Physician'), ('CARDIOLOGIST', 'Cardiologist'), ('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('ORTHOPEDIC', 'Orthopedic'), ('PEDIATRICIAN', 'Pediatrician'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
