# Generated by Django 4.2.28 on 2026-02-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_customuser_id_alter_customuser_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Professional biography and expertise", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="experience",
            field=models.PositiveIntegerField(
                default=0, help_text="Years of professional experience"
            ),
        ),
    ]
