# Generated by Django 4.2.27 on 2026-02-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0005_appointment_doctoravailability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctoravailability",
            options={
                "ordering": ["date", "day_of_week", "start_time"],
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="doctoravailability",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="day_of_week",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                null=True,
            ),
        ),
    ]
