# Generated by Django 4.2.27 on 2026-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0007_appointment_clinical_observations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
